// Code generated by ts-to-go at 52c59dbcbee274e523ef39e6c8be1bd5e110c2f1. DO NOT EDIT.

package output

func isExternalModuleNameRelative(moduleName string) bool {
	// TypeScript 1.0 spec (April 2014): 11.2.1
	// An external module name is "relative" if the first term is "." or "..".
	// Update: We also consider a path like `C:\foo.ts` "relative" because we do not search for it in `node_modules` or treat it as an ambient module.
	return pathIsRelative(moduleName) || isRootedDiskPath(moduleName)
}

func sortAndDeduplicateDiagnostics(diagnostics []T) SortedReadonlyArray[T] {
	return sortAndDeduplicate(diagnostics, compareDiagnostics, diagnosticsEqualityComparer)
}

/** @internal */

var targetToLibMap Map[ScriptTarget, string] = NewMap([] /* TODO(TS-TO-GO) inferred type [ScriptTarget.ESNext, string] | [ScriptTarget.ES2023, string] | [ScriptTarget.ES2022, string] | [ScriptTarget.ES2021, string] | [ScriptTarget.ES2020, string] | [ScriptTarget.ES2019, string] | [ScriptTarget.ES2018, string] | [ScriptTarget.ES2017, string] | [ScriptTarget.ES2016, string] | [ScriptTarget.ES2015, string] */ any{[]any{ScriptTargetESNext, "lib.esnext.full.d.ts"}, []any{ScriptTargetES2023, "lib.es2023.full.d.ts"}, []any{ScriptTargetES2022, "lib.es2022.full.d.ts"}, []any{ScriptTargetES2021, "lib.es2021.full.d.ts"}, []any{ScriptTargetES2020, "lib.es2020.full.d.ts"}, []any{ScriptTargetES2019, "lib.es2019.full.d.ts"}, []any{ScriptTargetES2018, "lib.es2018.full.d.ts"}, []any{ScriptTargetES2017, "lib.es2017.full.d.ts"}, []any{ScriptTargetES2016, "lib.es2016.full.d.ts"}, []any{ScriptTargetES2015, "lib.es6.d.ts"}})

func getDefaultLibFileName(options CompilerOptions) string {
	target := getEmitScriptTarget(options)
	switch target {
	case ScriptTargetESNext,
		ScriptTargetES2023,
		ScriptTargetES2022,
		ScriptTargetES2021,
		ScriptTargetES2020,
		ScriptTargetES2019,
		ScriptTargetES2018,
		ScriptTargetES2017,
		ScriptTargetES2016,
		ScriptTargetES2015:
		return targetToLibMap.get(target)
	default:
		return "lib.d.ts"
	}
}

func textSpanEnd(span TextSpan) number {
	return span.start + span.length
}

func textSpanIsEmpty(span TextSpan) bool {
	return span.length == 0
}

func textSpanContainsPosition(span TextSpan, position number) bool {
	return position >= span.start && position < textSpanEnd(span)
}

/** @internal */

func textRangeContainsPositionInclusive(range_ TextRange, position number) bool {
	return position >= range_.pos && position <= range_.end
}

// Returns true if 'span' contains 'other'.
func textSpanContainsTextSpan(span TextSpan, other TextSpan) bool {
	return other.start >= span.start && textSpanEnd(other) <= textSpanEnd(span)
}

/** @internal */

func textSpanContainsTextRange(span TextSpan, range_ TextRange) bool {
	return range_.pos >= span.start && range_.end <= textSpanEnd(span)
}

/** @internal */

func textRangeContainsTextSpan(range_ TextRange, span TextSpan) bool {
	return span.start >= range_.pos && textSpanEnd(span) <= range_.end
}

func textSpanOverlapsWith(span TextSpan, other TextSpan) bool {
	return textSpanOverlap(span, other) != nil
}

func textSpanOverlap(span1 TextSpan, span2 TextSpan) *TextSpan {
	overlap := textSpanIntersection(span1, span2)
	if overlap && overlap.length == 0 {
		return nil
	} else {
		return overlap
	}
}

func textSpanIntersectsWithTextSpan(span TextSpan, other TextSpan) bool {
	return decodedTextSpanIntersectsWith(span.start, span.length, other.start, other.length)
}

func textSpanIntersectsWith(span TextSpan, start number, length number) bool {
	return decodedTextSpanIntersectsWith(span.start, span.length, start, length)
}

func decodedTextSpanIntersectsWith(start1 number, length1 number, start2 number, length2 number) bool {
	end1 := start1 + length1
	end2 := start2 + length2
	return start2 <= end1 && end2 >= start1
}

func textSpanIntersectsWithPosition(span TextSpan, position number) bool {
	return position <= textSpanEnd(span) && position >= span.start
}

/** @internal */

func textRangeIntersectsWithTextSpan(range_ TextRange, span TextSpan) bool {
	return textSpanIntersectsWith(span, range_.pos, range_.end-range_.pos)
}

func textSpanIntersection(span1 TextSpan, span2 TextSpan) *TextSpan {
	start := max(span1.start, span2.start)
	end := min(textSpanEnd(span1), textSpanEnd(span2))
	if start <= end {
		return createTextSpanFromBounds(start, end)
	} else {
		return nil
	}
}

/**
 * Given an array of text spans, returns an equivalent sorted array of text spans
 * where no span overlaps or is adjacent to another span in the array.
 * @internal
 */

func normalizeSpans(spans []TextSpan) []TextSpan {
	spans = spans.filter(func(span TextSpan) bool {
		return span.length > 0
	}).sort(func(a TextSpan, b TextSpan) number {
		if a.start != b.start {
			return a.start - b.start
		} else {
			return a.length - b.length
		}
	})

	var result []TextSpan = []never{}
	i := 0
	for i < spans.length {
		span := spans[i]
		j := i + 1
		for j < spans.length && textSpanIntersectsWithTextSpan(span, spans[j]) {
			start := min(span.start, spans[j].start)
			end := max(textSpanEnd(span), textSpanEnd(spans[j]))
			span = createTextSpanFromBounds(start, end)
			j++
		}
		i = j
		result.push(span)
	}

	return result
}

func createTextSpan(start number, length number) TextSpan {
	if start < 0 {
		/* TODO(TS-TO-GO) Node ThrowStatement: throw new Error("start < 0"); */
	}
	if length < 0 {
		/* TODO(TS-TO-GO) Node ThrowStatement: throw new Error("length < 0"); */
	}

	return map[any]any{ /* TODO(TS-TO-GO): was object literal */
		"start":  start,
		"length": length,
	}
}

func createTextSpanFromBounds(start number, end number) TextSpan {
	return createTextSpan(start, end-start)
}

func textChangeRangeNewSpan(range_ TextChangeRange) TextSpan {
	return createTextSpan(range_.span.start, range_.newLength)
}

func textChangeRangeIsUnchanged(range_ TextChangeRange) bool {
	return textSpanIsEmpty(range_.span) && range_.newLength == 0
}

func createTextChangeRange(span TextSpan, newLength number) TextChangeRange {
	if newLength < 0 {
		/* TODO(TS-TO-GO) Node ThrowStatement: throw new Error("newLength < 0"); */
	}

	return map[any]any{ /* TODO(TS-TO-GO): was object literal */
		"span":      span,
		"newLength": newLength,
	}
}

var unchangedTextChangeRange TextChangeRange = createTextChangeRange(createTextSpan(0, 0), 0)

/**
 * Called to merge all the changes that occurred across several versions of a script snapshot
 * into a single change.  i.e. if a user keeps making successive edits to a script we will
 * have a text change from V1 to V2, V2 to V3, ..., Vn.
 *
 * This function will then merge those changes into a single change range valid between V1 and
 * Vn.
 */

func collapseTextChangeRangesAcrossMultipleVersions(changes []TextChangeRange) TextChangeRange {
	if changes.length == 0 {
		return unchangedTextChangeRange
	}

	if changes.length == 1 {
		return changes[0]
	}

	// We change from talking about { { oldStart, oldLength }, newLength } to { oldStart, oldEnd, newEnd }
	// as it makes things much easier to reason about.
	change0 := changes[0]

	oldStartN := change0.span.start
	oldEndN := textSpanEnd(change0.span)
	newEndN := oldStartN + change0.newLength

	for i := 1; i < changes.length; i++ {
		nextChange := changes[i]

		// Consider the following case:
		// i.e. two edits.  The first represents the text change range { { 10, 50 }, 30 }.  i.e. The span starting
		// at 10, with length 50 is reduced to length 30.  The second represents the text change range { { 30, 30 }, 40 }.
		// i.e. the span starting at 30 with length 30 is increased to length 40.
		//
		//      0         10        20        30        40        50        60        70        80        90        100
		//      -------------------------------------------------------------------------------------------------------
		//                |                                                 /
		//                |                                            /----
		//  T1            |                                       /----
		//                |                                  /----
		//                |                             /----
		//      -------------------------------------------------------------------------------------------------------
		//                                     |                            \
		//                                     |                               \
		//   T2                                |                                 \
		//                                     |                                   \
		//                                     |                                      \
		//      -------------------------------------------------------------------------------------------------------
		//
		// Merging these turns out to not be too difficult.  First, determining the new start of the change is trivial
		// it's just the min of the old and new starts.  i.e.:
		//
		//      0         10        20        30        40        50        60        70        80        90        100
		//      ------------------------------------------------------------*------------------------------------------
		//                |                                                 /
		//                |                                            /----
		//  T1            |                                       /----
		//                |                                  /----
		//                |                             /----
		//      ----------------------------------------$-------------------$------------------------------------------
		//                .                    |                            \
		//                .                    |                               \
		//   T2           .                    |                                 \
		//                .                    |                                   \
		//                .                    |                                      \
		//      ----------------------------------------------------------------------*--------------------------------
		//
		// (Note the dots represent the newly inferred start.
		// Determining the new and old end is also pretty simple.  Basically it boils down to paying attention to the
		// absolute positions at the asterisks, and the relative change between the dollar signs. Basically, we see
		// which if the two $'s precedes the other, and we move that one forward until they line up.  in this case that
		// means:
		//
		//      0         10        20        30        40        50        60        70        80        90        100
		//      --------------------------------------------------------------------------------*----------------------
		//                |                                                                     /
		//                |                                                                /----
		//  T1            |                                                           /----
		//                |                                                      /----
		//                |                                                 /----
		//      ------------------------------------------------------------$------------------------------------------
		//                .                    |                            \
		//                .                    |                               \
		//   T2           .                    |                                 \
		//                .                    |                                   \
		//                .                    |                                      \
		//      ----------------------------------------------------------------------*--------------------------------
		//
		// In other words (in this case), we're recognizing that the second edit happened after where the first edit
		// ended with a delta of 20 characters (60 - 40).  Thus, if we go back in time to where the first edit started
		// that's the same as if we started at char 80 instead of 60.
		//
		// As it so happens, the same logic applies if the second edit precedes the first edit.  In that case rather
		// than pushing the first edit forward to match the second, we'll push the second edit forward to match the
		// first.
		//
		// In this case that means we have { oldStart: 10, oldEnd: 80, newEnd: 70 } or, in TextChangeRange
		// semantics: { { start: 10, length: 70 }, newLength: 60 }
		//
		// The math then works out as follows.
		// If we have { oldStart1, oldEnd1, newEnd1 } and { oldStart2, oldEnd2, newEnd2 } then we can compute the
		// final result like so:
		//
		// {
		//      oldStart3: Min(oldStart1, oldStart2),
		//      oldEnd3: Max(oldEnd1, oldEnd1 + (oldEnd2 - newEnd1)),
		//      newEnd3: Max(newEnd2, newEnd2 + (newEnd1 - oldEnd2))
		// }

		oldStart1 := oldStartN
		oldEnd1 := oldEndN
		newEnd1 := newEndN

		oldStart2 := nextChange.span.start
		oldEnd2 := textSpanEnd(nextChange.span)
		newEnd2 := oldStart2 + nextChange.newLength

		oldStartN = min(oldStart1, oldStart2)
		oldEndN = max(oldEnd1, oldEnd1+(oldEnd2-newEnd1))
		newEndN = max(newEnd2, newEnd2+(newEnd1-oldEnd2))
	}

	return createTextChangeRange(createTextSpanFromBounds(oldStartN, oldEndN) /*newLength*/, newEndN-oldStartN)
}

func getTypeParameterOwner(d Declaration) Declaration {
	if d && d.kind == SyntaxKindTypeParameter {
		for current := d; current; current = current.parent {
			if isFunctionLike(current) || isClassLike(current) || current.kind == SyntaxKindInterfaceDeclaration {
				return current.(Declaration)
			}
		}
	}
}

type ParameterPropertyDeclaration /* TODO(TS-TO-GO) TypeNode IntersectionType: ParameterDeclaration & { parent: ConstructorDeclaration; name: Identifier; } */ any

func isParameterPropertyDeclaration(node *Node, parent *Node) bool {
	return isParameter(node) && hasSyntacticModifier(node, ModifierFlagsParameterPropertyModifier) && parent.kind == SyntaxKindConstructor
}

func isEmptyBindingPattern(node BindingName) bool {
	if isBindingPattern(node) {
		return every(node.elements, isEmptyBindingElement)
	}
	return false
}

// TODO(jakebailey): It is very weird that we have BindingElement and ArrayBindingElement;
// we should have ObjectBindingElement and ArrayBindingElement, which are both BindingElement,
// just like BindingPattern is a ObjectBindingPattern or a ArrayBindingPattern.
func isEmptyBindingElement(node /* TODO(TS-TO-GO) TypeNode UnionType: BindingElement | ArrayBindingElement */ any) bool {
	if isOmittedExpression(node) {
		return true
	}
	return isEmptyBindingPattern(node.name)
}

func walkUpBindingElementsAndPatterns(binding BindingElement) /* TODO(TS-TO-GO) TypeNode UnionType: VariableDeclaration | ParameterDeclaration */ any {
	node := binding.parent
	for isBindingElement(node.parent) {
		node = node.parent.parent
	}
	return node.parent
}

func getCombinedFlags(node *Node, getFlags func(n *Node) number) number {
	if isBindingElement(node) {
		node = walkUpBindingElementsAndPatterns(node)
	}
	flags := getFlags(node)
	if node.kind == SyntaxKindVariableDeclaration {
		node = node.parent
	}
	if node && node.kind == SyntaxKindVariableDeclarationList {
		flags |= getFlags(node)
		node = node.parent
	}
	if node && node.kind == SyntaxKindVariableStatement {
		flags |= getFlags(node)
	}
	return flags
}

func getCombinedModifierFlags(node Declaration) ModifierFlags {
	return getCombinedFlags(node, getEffectiveModifierFlags)
}

/** @internal */

func getCombinedNodeFlagsAlwaysIncludeJSDoc(node Declaration) ModifierFlags {
	return getCombinedFlags(node, getEffectiveModifierFlagsAlwaysIncludeJSDoc)
}

// Returns the node flags for this node and all relevant parent nodes.  This is done so that
// nodes like variable declarations and binding elements can returned a view of their flags
// that includes the modifiers from their container.  i.e. flags like export/declare aren't
// stored on the variable declaration directly, but on the containing variable statement
// (if it has one).  Similarly, flags for let/const are stored on the variable declaration
// list.  By calling this function, all those flags are combined so that the client can treat
// the node as if it actually had those flags.
func getCombinedNodeFlags(node *Node) NodeFlags {
	return getCombinedFlags(node, getNodeFlags)
}

func getNodeFlags(node *Node) NodeFlags {
	return node.flags
}

/** @internal */

var supportedLocaleDirectories = []any{"cs", "de", "es", "fr", "it", "ja", "ko", "pl", "pt-br", "ru", "tr", "zh-cn", "zh-tw"}.(const_)

/**
 * Checks to see if the locale is in the appropriate format,
 * and if it is, attempts to set the appropriate language.
 */

func validateLocaleAndSetLanguage(locale string, sys /* TODO(TS-TO-GO) TypeNode TypeLiteral: { getExecutingFilePath(): string; resolvePath(path: string): string; fileExists(fileName: string): boolean; readFile(fileName: string): string | undefined; } */ any, errors []Diagnostic) {
	lowerCaseLocale := locale.toLowerCase()
	matchResult := regexp.MustParse(`^([a-z]+)(?:[_-]([a-z]+))?$`).exec(lowerCaseLocale)

	if !matchResult {
		if errors {
			errors.push(createCompilerDiagnostic(Diagnostics.Locale_must_be_of_the_form_language_or_language_territory_For_example_0_or_1, "en", "ja-jp"))
		}
		return
	}

	language := matchResult[1]
	territory := matchResult[2]

	// First try the entire locale, then fall back to just language if that's all we have.
	// Either ways do not fail, and fallback to the English diagnostic strings.
	if contains(supportedLocaleDirectories, lowerCaseLocale) && !trySetLanguageAndTerritory(language, territory, errors) {
		trySetLanguageAndTerritory(language /*territory*/, nil, errors)
	}

	// Set the UI locale for string collation
	setUILocale(locale)

	trySetLanguageAndTerritory := func(language string, territory *string, errors []Diagnostic) bool {
		compilerFilePath := normalizePath(sys.getExecutingFilePath())
		containingDirectoryPath := getDirectoryPath(compilerFilePath)

		filePath := combinePaths(containingDirectoryPath, language)

		if territory {
			filePath = filePath + "-" + territory
		}

		filePath = sys.resolvePath(combinePaths(filePath, "diagnosticMessages.generated.json"))

		if !sys.fileExists(filePath) {
			return false
		}

		// TODO: Add codePage support for readFile?
		var fileContents *string = ""
		{ // try
			fileContents = sys.readFile(filePath)
		}
		{ // catch
			if errors {
				errors.push(createCompilerDiagnostic(Diagnostics.Unable_to_open_file_0, filePath))
			}
			return false
		}
		{ // try
			// this is a global mutation (or live binding update)!
			setLocalizedDiagnosticMessages(JSON.parse(fileContents))
		}
		{ // catch
			if errors {
				errors.push(createCompilerDiagnostic(Diagnostics.Corrupted_locale_file_0, filePath))
			}
			return false
		}

		return true
	}

}

/* OVERLOAD: export function getOriginalNode(node: Node): Node; */
/* OVERLOAD: export function getOriginalNode<T extends Node>(node: Node, nodeTest: (node: Node) => node is T): T; */
/* OVERLOAD: export function getOriginalNode(node: Node | undefined): Node | undefined; */
/* OVERLOAD: export function getOriginalNode<T extends Node>(node: Node | undefined, nodeTest: (node: Node) => node is T): T | undefined; */
func getOriginalNode(node *Node, nodeTest func(node *Node) /* TODO(TS-TO-GO) TypeNode TypePredicate: node is T */ any) *T {
	if node {
		for node.original != nil {
			node = node.original
		}
	}

	if !node || !nodeTest {
		return node /* as T | undefined */
	}

	if nodeTest(node) {
		return node
	} else {
		return nil
	}
}

/**
 * Iterates through the parent chain of a node and performs the callback on each parent until the callback
 * returns a truthy value, then returns that value.
 * If no such value is found, it applies the callback until the parent pointer is undefined or the callback returns "quit"
 * At that point findAncestor returns undefined.
 */

/* OVERLOAD: export function findAncestor<T extends Node>(node: Node | undefined, callback: (element: Node) => element is T): T | undefined; */
/* OVERLOAD: export function findAncestor(node: Node | undefined, callback: (element: Node) => boolean | "quit"): Node | undefined; */
func findAncestor(node *Node, callback func(element *Node) /* TODO(TS-TO-GO) TypeNode UnionType: boolean | "quit" */ any) *Node {
	for node {
		result := callback(node)
		if result == "quit" {
			return nil
		} else if result {
			return node
		}
		node = node.parent
	}
	return nil
}

/**
 * Gets a value indicating whether a node originated in the parse tree.
 *
 * @param node The node to test.
 */

func isParseTreeNode(node *Node) bool {
	return (node.flags & NodeFlagsSynthesized) == 0
}

/**
 * Gets the original parse tree node for a node.
 *
 * @param node The original node.
 * @returns The original parse tree node if found; otherwise, undefined.
 */

/* OVERLOAD: export function getParseTreeNode(node: Node | undefined): Node | undefined; */
/**
 * Gets the original parse tree node for a node.
 *
 * @param node The original node.
 * @param nodeTest A callback used to ensure the correct type of parse tree node is returned.
 * @returns The original parse tree node if found; otherwise, undefined.
 */

/* OVERLOAD: export function getParseTreeNode<T extends Node>(node: T | undefined, nodeTest?: (node: Node) => node is T): T | undefined; */
func getParseTreeNode(node *Node, nodeTest func(node *Node) bool) *Node {
	if node == nil || isParseTreeNode(node) {
		return node
	}

	node = node.original
	for node {
		if isParseTreeNode(node) {
			if !nodeTest || nodeTest(node) {
				return node
			} else {
				return nil
			}
		}
		node = node.original
	}
}

/** Add an extra underscore to identifiers that start with two underscores to avoid issues with magic names like '__proto__' */

func escapeLeadingUnderscores(identifier string) string {
	return (ifElse(identifier.length >= 2 && identifier.charCodeAt(0) == CharacterCodes_ && identifier.charCodeAt(1) == CharacterCodes_, "_"+identifier, identifier)).(string)
}

/**
 * Remove extra underscore from escaped identifier text content.
 *
 * @param identifier The escaped identifier text.
 * @returns The unescaped identifier text.
 */

func unescapeLeadingUnderscores(identifier string) string {
	id := identifier /* as string */
	if id.length >= 3 && id.charCodeAt(0) == CharacterCodes_ && id.charCodeAt(1) == CharacterCodes_ && id.charCodeAt(2) == CharacterCodes_ {
		return id.substr(1)
	} else {
		return id
	}
}

func idText(identifierOrPrivateName /* TODO(TS-TO-GO) TypeNode UnionType: Identifier | PrivateIdentifier */ any) string {
	return unescapeLeadingUnderscores(identifierOrPrivateName.escapedText)
}

/**
 * If the text of an Identifier matches a keyword (including contextual and TypeScript-specific keywords), returns the
 * SyntaxKind for the matching keyword.
 */

func identifierToKeywordKind(node Identifier) *KeywordSyntaxKind {
	token := stringToToken(node.escapedText /* as string */)
	if token {
		return tryCast(token, isKeyword)
	} else {
		return nil
	}
}

func symbolName(symbol *Symbol) string {
	if symbol.valueDeclaration && isPrivateIdentifierClassElementDeclaration(symbol.valueDeclaration) {
		return idText(symbol.valueDeclaration.name)
	}
	return unescapeLeadingUnderscores(symbol.escapedName)
}

/**
 * A JSDocTypedef tag has an _optional_ name field - if a name is not directly present, we should
 * attempt to draw the name from the node the declaration is on (as that declaration is what its' symbol
 * will be merged with)
 */

func nameForNamelessJSDocTypedef(declaration /* TODO(TS-TO-GO) TypeNode UnionType: JSDocTypedefTag | JSDocEnumTag */ any) /* TODO(TS-TO-GO) TypeNode UnionType: Identifier | PrivateIdentifier | undefined */ any {
	hostNode := declaration.parent.parent
	if !hostNode {
		return nil
	}
	// Covers classes, functions - any named declaration host node
	if isDeclaration(hostNode) {
		return getDeclarationIdentifier(hostNode)
	}
	// Covers remaining cases (returning undefined if none match).
	switch hostNode.kind {
	case SyntaxKindVariableStatement:
		if hostNode.declarationList && hostNode.declarationList.declarations[0] {
			return getDeclarationIdentifier(hostNode.declarationList.declarations[0])
		}
	case SyntaxKindExpressionStatement:
		expr := hostNode.expression
		if expr.kind == SyntaxKindBinaryExpression && (expr.(BinaryExpression)).operatorToken.kind == SyntaxKindEqualsToken {
			expr = (expr.(BinaryExpression)).left
		}
		switch expr.kind {
		case SyntaxKindPropertyAccessExpression:
			return (expr.(PropertyAccessExpression)).name
		case SyntaxKindElementAccessExpression:
			arg := (expr.(ElementAccessExpression)).argumentExpression
			if isIdentifier(arg) {
				return arg
			}
		}
	case SyntaxKindParenthesizedExpression:
		return getDeclarationIdentifier(hostNode.expression)
	case SyntaxKindLabeledStatement:
		if isDeclaration(hostNode.statement) || isExpression(hostNode.statement) {
			return getDeclarationIdentifier(hostNode.statement)
		}
	}
}

func getDeclarationIdentifier(node /* TODO(TS-TO-GO) TypeNode UnionType: Declaration | Expression */ any) *Identifier {
	name := getNameOfDeclaration(node)
	if name && isIdentifier(name) {
		return name
	} else {
		return nil
	}
}

/** @internal */

func nodeHasName(statement *Node, name Identifier) bool {
	if isNamedDeclaration(statement) && isIdentifier(statement.name) && idText(statement.name.(Identifier)) == idText(name) {
		return true
	}
	if isVariableStatement(statement) && some(statement.declarationList.declarations, func(d VariableDeclaration) bool {
		return nodeHasName(d, name)
	}) {
		return true
	}
	return false
}

func getNameOfJSDocTypedef(declaration JSDocTypedefTag) /* TODO(TS-TO-GO) TypeNode UnionType: Identifier | PrivateIdentifier | undefined */ any {
	return declaration.name || nameForNamelessJSDocTypedef(declaration)
}

/** @internal */

func isNamedDeclaration(node *Node) bool {
	return !!(node.(NamedDeclaration)).name
	// A 'name' property should always be a DeclarationName.
}

/** @internal */

func getNonAssignedNameOfDeclaration(declaration /* TODO(TS-TO-GO) TypeNode UnionType: Declaration | Expression */ any) *DeclarationName {
	switch declaration.kind {
	case SyntaxKindIdentifier:
		return declaration.(Identifier)
	case SyntaxKindJSDocPropertyTag,
		SyntaxKindJSDocParameterTag:
		TODO_IDENTIFIER := declaration.(JSDocPropertyLikeTag)
		if name.kind == SyntaxKindQualifiedName {
			return name.right
		}
	case SyntaxKindCallExpression,
		SyntaxKindBinaryExpression:
		expr := declaration /* as BinaryExpression | CallExpression */
		switch getAssignmentDeclarationKind(expr) {
		case AssignmentDeclarationKindExportsProperty,
			AssignmentDeclarationKindThisProperty,
			AssignmentDeclarationKindProperty,
			AssignmentDeclarationKindPrototypeProperty:
			return getElementOrPropertyAccessArgumentExpressionOrName((expr.(BinaryExpression)).left.(AccessExpression))
		case AssignmentDeclarationKindObjectDefinePropertyValue,
			AssignmentDeclarationKindObjectDefinePropertyExports,
			AssignmentDeclarationKindObjectDefinePrototypeProperty:
			return (expr.(BindableObjectDefinePropertyCall)).arguments[1]
		default:
			return nil
		}
		fallthrough
	case SyntaxKindJSDocTypedefTag:
		return getNameOfJSDocTypedef(declaration.(JSDocTypedefTag))
	case SyntaxKindJSDocEnumTag:
		return nameForNamelessJSDocTypedef(declaration.(JSDocEnumTag))
	case SyntaxKindExportAssignment:
		TODO_IDENTIFIER := declaration.(ExportAssignment)
		if isIdentifier(expression) {
			return expression
		} else {
			return nil
		}
	case SyntaxKindElementAccessExpression:
		expr := declaration.(ElementAccessExpression)
		if isBindableStaticElementAccessExpression(expr) {
			return expr.argumentExpression
		}
	}
	return (declaration.(NamedDeclaration)).name
}

func getNameOfDeclaration(declaration /* TODO(TS-TO-GO) TypeNode UnionType: Declaration | Expression | undefined */ any) *DeclarationName {
	if declaration == nil {
		return nil
	}
	return getNonAssignedNameOfDeclaration(declaration) || (ifElse(isFunctionExpression(declaration) || isArrowFunction(declaration) || isClassExpression(declaration), getAssignedName(declaration), nil))
}

/** @internal */

func getAssignedName(node *Node) *DeclarationName {
	if !node.parent {
		return nil
	} else if isPropertyAssignment(node.parent) || isBindingElement(node.parent) {
		return node.parent.name
	} else if isBinaryExpression(node.parent) && node == node.parent.right {
		if isIdentifier(node.parent.left) {
			return node.parent.left
		} else if isAccessExpression(node.parent.left) {
			return getElementOrPropertyAccessArgumentExpressionOrName(node.parent.left)
		}
	} else if isVariableDeclaration(node.parent) && isIdentifier(node.parent.name) {
		return node.parent.name
	}
}

func getDecorators(node HasDecorators) *[]Decorator {
	if hasDecorators(node) {
		return filter(node.modifiers, isDecorator)
	}
}

func getModifiers(node HasModifiers) *[]Modifier {
	if hasSyntacticModifier(node, ModifierFlagsModifier) {
		return filter(node.modifiers, isModifier)
	}
}

func getJSDocParameterTagsWorker(param ParameterDeclaration, noCache bool) []JSDocParameterTag {
	if param.name {
		if isIdentifier(param.name) {
			name := param.name.escapedText
			return getJSDocTagsWorker(param.parent, noCache).filter(func(tag JSDocTag) bool {
				return isJSDocParameterTag(tag) && isIdentifier(tag.name) && tag.name.escapedText == name
			})
		} else {
			i := param.parent.parameters.indexOf(param)
			Debug.assert(i > -1, "Parameters should always be in their parents' parameter list")
			paramTags := getJSDocTagsWorker(param.parent, noCache).filter(isJSDocParameterTag)
			if i < paramTags.length {
				return []JSDocParameterTag{paramTags[i]}
			}
		}
	}
	// return empty array for: out-of-order binding patterns and JSDoc function syntax, which has un-named parameters
	return emptyArray
}

/**
 * Gets the JSDoc parameter tags for the node if present.
 *
 * @remarks Returns any JSDoc param tag whose name matches the provided
 * parameter, whether a param tag on a containing function
 * expression, or a param tag on a variable declaration whose
 * initializer is the containing function. The tags closest to the
 * node are returned first, so in the previous example, the param
 * tag on the containing function expression would be first.
 *
 * For binding patterns, parameter tags are matched by position.
 */

func getJSDocParameterTags(param ParameterDeclaration) []JSDocParameterTag {
	return getJSDocParameterTagsWorker(param /*noCache*/, false)
}

/** @internal */

func getJSDocParameterTagsNoCache(param ParameterDeclaration) []JSDocParameterTag {
	return getJSDocParameterTagsWorker(param /*noCache*/, true)
}

func getJSDocTypeParameterTagsWorker(param TypeParameterDeclaration, noCache bool) []JSDocTemplateTag {
	name := param.name.escapedText
	return getJSDocTagsWorker(param.parent, noCache).filter(func(tag JSDocTag) bool {
		return isJSDocTemplateTag(tag) && tag.typeParameters.some(func(tp TypeParameterDeclaration) bool {
			return tp.name.escapedText == name
		})
	})
}

/**
 * Gets the JSDoc type parameter tags for the node if present.
 *
 * @remarks Returns any JSDoc template tag whose names match the provided
 * parameter, whether a template tag on a containing function
 * expression, or a template tag on a variable declaration whose
 * initializer is the containing function. The tags closest to the
 * node are returned first, so in the previous example, the template
 * tag on the containing function expression would be first.
 */

func getJSDocTypeParameterTags(param TypeParameterDeclaration) []JSDocTemplateTag {
	return getJSDocTypeParameterTagsWorker(param /*noCache*/, false)
}

/** @internal */

func getJSDocTypeParameterTagsNoCache(param TypeParameterDeclaration) []JSDocTemplateTag {
	return getJSDocTypeParameterTagsWorker(param /*noCache*/, true)
}

/**
 * Return true if the node has JSDoc parameter tags.
 *
 * @remarks Includes parameter tags that are not directly on the node,
 * for example on a variable declaration whose initializer is a function expression.
 */

func hasJSDocParameterTags(node /* TODO(TS-TO-GO) TypeNode UnionType: FunctionLikeDeclaration | SignatureDeclaration */ any) bool {
	return !!getFirstJSDocTag(node, isJSDocParameterTag)
}

/** Gets the JSDoc augments tag for the node if present */

func getJSDocAugmentsTag(node *Node) *JSDocAugmentsTag {
	return getFirstJSDocTag(node, isJSDocAugmentsTag)
}

/** Gets the JSDoc implements tags for the node if present */

func getJSDocImplementsTags(node *Node) []JSDocImplementsTag {
	return getAllJSDocTags(node, isJSDocImplementsTag)
}

/** Gets the JSDoc class tag for the node if present */

func getJSDocClassTag(node *Node) *JSDocClassTag {
	return getFirstJSDocTag(node, isJSDocClassTag)
}

/** Gets the JSDoc public tag for the node if present */

func getJSDocPublicTag(node *Node) *JSDocPublicTag {
	return getFirstJSDocTag(node, isJSDocPublicTag)
}

/** @internal */

func getJSDocPublicTagNoCache(node *Node) *JSDocPublicTag {
	return getFirstJSDocTag(node, isJSDocPublicTag /*noCache*/, true)
}

/** Gets the JSDoc private tag for the node if present */

func getJSDocPrivateTag(node *Node) *JSDocPrivateTag {
	return getFirstJSDocTag(node, isJSDocPrivateTag)
}

/** @internal */

func getJSDocPrivateTagNoCache(node *Node) *JSDocPrivateTag {
	return getFirstJSDocTag(node, isJSDocPrivateTag /*noCache*/, true)
}

/** Gets the JSDoc protected tag for the node if present */

func getJSDocProtectedTag(node *Node) *JSDocProtectedTag {
	return getFirstJSDocTag(node, isJSDocProtectedTag)
}

/** @internal */

func getJSDocProtectedTagNoCache(node *Node) *JSDocProtectedTag {
	return getFirstJSDocTag(node, isJSDocProtectedTag /*noCache*/, true)
}

/** Gets the JSDoc protected tag for the node if present */

func getJSDocReadonlyTag(node *Node) *JSDocReadonlyTag {
	return getFirstJSDocTag(node, isJSDocReadonlyTag)
}

/** @internal */

func getJSDocReadonlyTagNoCache(node *Node) *JSDocReadonlyTag {
	return getFirstJSDocTag(node, isJSDocReadonlyTag /*noCache*/, true)
}

func getJSDocOverrideTagNoCache(node *Node) *JSDocOverrideTag {
	return getFirstJSDocTag(node, isJSDocOverrideTag /*noCache*/, true)
}

/** Gets the JSDoc deprecated tag for the node if present */

func getJSDocDeprecatedTag(node *Node) *JSDocDeprecatedTag {
	return getFirstJSDocTag(node, isJSDocDeprecatedTag)
}

/** @internal */

func getJSDocDeprecatedTagNoCache(node *Node) *JSDocDeprecatedTag {
	return getFirstJSDocTag(node, isJSDocDeprecatedTag /*noCache*/, true)
}

/** Gets the JSDoc enum tag for the node if present */

func getJSDocEnumTag(node *Node) *JSDocEnumTag {
	return getFirstJSDocTag(node, isJSDocEnumTag)
}

/** Gets the JSDoc this tag for the node if present */

func getJSDocThisTag(node *Node) *JSDocThisTag {
	return getFirstJSDocTag(node, isJSDocThisTag)
}

/** Gets the JSDoc return tag for the node if present */

func getJSDocReturnTag(node *Node) *JSDocReturnTag {
	return getFirstJSDocTag(node, isJSDocReturnTag)
}

/** Gets the JSDoc template tag for the node if present */

func getJSDocTemplateTag(node *Node) *JSDocTemplateTag {
	return getFirstJSDocTag(node, isJSDocTemplateTag)
}

func getJSDocSatisfiesTag(node *Node) *JSDocSatisfiesTag {
	return getFirstJSDocTag(node, isJSDocSatisfiesTag)
}

/** Gets the JSDoc type tag for the node if present and valid */

func getJSDocTypeTag(node *Node) *JSDocTypeTag {
	// We should have already issued an error if there were multiple type jsdocs, so just use the first one.
	tag := getFirstJSDocTag(node, isJSDocTypeTag)
	if tag && tag.typeExpression && tag.typeExpression.type_ {
		return tag
	}
	return nil
}

/**
 * Gets the type node for the node if provided via JSDoc.
 *
 * @remarks The search includes any JSDoc param tag that relates
 * to the provided parameter, for example a type tag on the
 * parameter itself, or a param tag on a containing function
 * expression, or a param tag on a variable declaration whose
 * initializer is the containing function. The tags closest to the
 * node are examined first, so in the previous example, the type
 * tag directly on the node would be returned.
 */

func getJSDocType(node *Node) *TypeNode {
	var tag /* TODO(TS-TO-GO) TypeNode UnionType: JSDocTypeTag | JSDocParameterTag | undefined */ any = getFirstJSDocTag(node, isJSDocTypeTag)
	if !tag && isParameter(node) {
		tag = find(getJSDocParameterTags(node), func(tag JSDocParameterTag) bool {
			return !!tag.typeExpression
		})
	}

	return tag && tag.typeExpression && tag.typeExpression.type_
}

/**
 * Gets the return type node for the node if provided via JSDoc return tag or type tag.
 *
 * @remarks `getJSDocReturnTag` just gets the whole JSDoc tag. This function
 * gets the type from inside the braces, after the fat arrow, etc.
 */

func getJSDocReturnType(node *Node) *TypeNode {
	returnTag := getJSDocReturnTag(node)
	if returnTag && returnTag.typeExpression {
		return returnTag.typeExpression.type_
	}
	typeTag := getJSDocTypeTag(node)
	if typeTag && typeTag.typeExpression {
		type_ := typeTag.typeExpression.type_
		if isTypeLiteralNode(type_) {
			sig := find(type_.members, isCallSignatureDeclaration)
			return sig && sig.type_
		}
		if isFunctionTypeNode(type_) || isJSDocFunctionType(type_) {
			return type_.type_
		}
	}
}

func getJSDocTagsWorker(node *Node, noCache bool) []JSDocTag {
	if !canHaveJSDoc(node) {
		return emptyArray
	}
	tags := node.jsDoc. /* ? */ jsDocCache
	// If cache is 'null', that means we did the work of searching for JSDoc tags and came up with nothing.
	if tags == nil || noCache {
		comments := getJSDocCommentsAndTags(node, noCache)
		Debug.assert(comments.length < 2 || comments[0] != comments[1])
		tags = flatMap(comments, func(j /* TODO(TS-TO-GO) inferred type JSDocTag | JSDoc */ any) * /* TODO(TS-TO-GO) inferred type JSDocTag | NodeArray<JSDocTag> */ any {
			if isJSDoc(j) {
				return j.tags
			} else {
				return j
			}
		})
		if !noCache {
			/* TODO(TS-TO-GO) QuestionQuestionEqualsToken BinaryExpression: node.jsDoc ??= [] */ TODO
			node.jsDoc.jsDocCache = tags
		}
	}
	return tags
}

/** Get all JSDoc tags related to a node, including those on parent nodes. */

func getJSDocTags(node *Node) []JSDocTag {
	return getJSDocTagsWorker(node /*noCache*/, false)
}

/** Get the first JSDoc tag of a specified kind, or undefined if not present. */

func getFirstJSDocTag(node *Node, predicate func(tag JSDocTag) /* TODO(TS-TO-GO) TypeNode TypePredicate: tag is T */ any, noCache bool) *T {
	return find(getJSDocTagsWorker(node, noCache), predicate)
}

/** Gets all JSDoc tags that match a specified predicate */

func getAllJSDocTags(node *Node, predicate func(tag JSDocTag) /* TODO(TS-TO-GO) TypeNode TypePredicate: tag is T */ any) []T {
	return getJSDocTags(node).filter(predicate)
}

/** Gets all JSDoc tags of a specified kind */

func getAllJSDocTagsOfKind(node *Node, kind SyntaxKind) []JSDocTag {
	return getJSDocTags(node).filter(func(doc JSDocTag) bool {
		return doc.kind == kind
	})
}

/** Gets the text of a jsdoc comment, flattening links to their text. */

func getTextOfJSDocComment(comment /* TODO(TS-TO-GO) TypeNode UnionType: string | NodeArray<JSDocComment> */ any) *string {
	if /* TODO(TS-TO-GO) Node TypeOfExpression: typeof comment */ TODO == "string" {
		return comment
	} else {
		return comment. /* ? */ map_(func(c JSDocComment) string {
			if c.kind == SyntaxKindJSDocText {
				return c.text
			} else {
				return formatJSDocLink(c)
			}
		}).join("")
	}
}

func formatJSDocLink(link /* TODO(TS-TO-GO) TypeNode UnionType: JSDocLink | JSDocLinkCode | JSDocLinkPlain */ any) string {
	var kind /* TODO(TS-TO-GO) inferred type "link" | "linkcode" | "linkplain" */ any
	switch {
	case link.kind == SyntaxKindJSDocLink:
		kind = "link"
	case link.kind == SyntaxKindJSDocLinkCode:
		kind = "linkcode"
	default:
		kind = "linkplain"
	}
	var name string
	if link.name {
		name = entityNameToString(link.name)
	} else {
		name = ""
	}
	var space /* TODO(TS-TO-GO) inferred type "" | " " */ any
	if link.name && (link.text == "" || link.text.startsWith("://")) {
		space = ""
	} else {
		space = " "
	}
	return __TEMPLATE__("{@", kind, " ", name, space, link.text, "}")
}

/**
 * Gets the effective type parameters. If the node was parsed in a
 * JavaScript file, gets the type parameters from the `@template` tag from JSDoc.
 *
 * This does *not* return type parameters from a jsdoc reference to a generic type, eg
 *
 * type Id = <T>(x: T) => T
 * /** @type {Id} /
 * function id(x) { return x }
 */

func getEffectiveTypeParameterDeclarations(node DeclarationWithTypeParameters) []TypeParameterDeclaration {
	if isJSDocSignature(node) {
		if isJSDocOverloadTag(node.parent) {
			jsDoc := getJSDocRoot(node.parent)
			if jsDoc && length(jsDoc.tags) {
				return flatMap(jsDoc.tags, func(tag JSDocTag) *NodeArray[TypeParameterDeclaration] {
					if isJSDocTemplateTag(tag) {
						return tag.typeParameters
					} else {
						return nil
					}
				})
			}
		}
		return emptyArray
	}
	if isJSDocTypeAlias(node) {
		Debug.assert(node.parent.kind == SyntaxKindJSDoc)
		return flatMap(node.parent.tags, func(tag JSDocTag) *NodeArray[TypeParameterDeclaration] {
			if isJSDocTemplateTag(tag) {
				return tag.typeParameters
			} else {
				return nil
			}
		})
	}
	if node.typeParameters {
		return node.typeParameters
	}
	if canHaveIllegalTypeParameters(node) && node.typeParameters {
		return node.typeParameters
	}
	if isInJSFile(node) {
		decls := getJSDocTypeParameterDeclarations(node)
		if decls.length {
			return decls
		}
		typeTag := getJSDocType(node)
		if typeTag && isFunctionTypeNode(typeTag) && typeTag.typeParameters {
			return typeTag.typeParameters
		}
	}
	return emptyArray
}

func getEffectiveConstraintOfTypeParameter(node TypeParameterDeclaration) *TypeNode {
	switch {
	case node.constraint:
		return node.constraint
	case isJSDocTemplateTag(node.parent) && node == node.parent.typeParameters[0]:
		return node.parent.constraint
	default:
		return nil
	}
}

// #region

func isMemberName(node *Node) bool {
	return node.kind == SyntaxKindIdentifier || node.kind == SyntaxKindPrivateIdentifier
}

/** @internal */

func isGetOrSetAccessorDeclaration(node *Node) bool {
	return node.kind == SyntaxKindSetAccessor || node.kind == SyntaxKindGetAccessor
}

func isPropertyAccessChain(node *Node) bool {
	return isPropertyAccessExpression(node) && !!(node.flags & NodeFlagsOptionalChain)
}

func isElementAccessChain(node *Node) bool {
	return isElementAccessExpression(node) && !!(node.flags & NodeFlagsOptionalChain)
}

func isCallChain(node *Node) bool {
	return isCallExpression(node) && !!(node.flags & NodeFlagsOptionalChain)
}

func isOptionalChain(node *Node) bool {
	kind := node.kind
	return !!(node.flags & NodeFlagsOptionalChain) && (kind == SyntaxKindPropertyAccessExpression || kind == SyntaxKindElementAccessExpression || kind == SyntaxKindCallExpression || kind == SyntaxKindNonNullExpression)
}

/** @internal */

func isOptionalChainRoot(node *Node) bool {
	return isOptionalChain(node) && !isNonNullExpression(node) && !!node.questionDotToken
}

/**
 * Determines whether a node is the expression preceding an optional chain (i.e. `a` in `a?.b`).
 *
 * @internal
 */

func isExpressionOfOptionalChainRoot(node *Node) bool {
	return isOptionalChainRoot(node.parent) && node.parent.expression == node
}

/**
 * Determines whether a node is the outermost `OptionalChain` in an ECMAScript `OptionalExpression`:
 *
 * 1. For `a?.b.c`, the outermost chain is `a?.b.c` (`c` is the end of the chain starting at `a?.`)
 * 2. For `a?.b!`, the outermost chain is `a?.b` (`b` is the end of the chain starting at `a?.`)
 * 3. For `(a?.b.c).d`, the outermost chain is `a?.b.c` (`c` is the end of the chain starting at `a?.` since parens end the chain)
 * 4. For `a?.b.c?.d`, both `a?.b.c` and `a?.b.c?.d` are outermost (`c` is the end of the chain starting at `a?.`, and `d` is
 *   the end of the chain starting at `c?.`)
 * 5. For `a?.(b?.c).d`, both `b?.c` and `a?.(b?.c)d` are outermost (`c` is the end of the chain starting at `b`, and `d` is
 *   the end of the chain starting at `a?.`)
 *
 * @internal
 */

func isOutermostOptionalChain(node OptionalChain) bool {
	return !isOptionalChain(node.parent) || isOptionalChainRoot(node.parent) || node != node.parent.expression
	// case 5
}

func isNullishCoalesce(node *Node) bool {
	return node.kind == SyntaxKindBinaryExpression && (node.(BinaryExpression)).operatorToken.kind == SyntaxKindQuestionQuestionToken
}

func isConstTypeReference(node *Node) bool {
	return isTypeReferenceNode(node) && isIdentifier(node.typeName) && node.typeName.escapedText == "const" && !node.typeArguments
}

/* OVERLOAD: export function skipPartiallyEmittedExpressions(node: Expression): Expression; */
/* OVERLOAD: export function skipPartiallyEmittedExpressions(node: Node): Node; */
func skipPartiallyEmittedExpressions(node *Node) *Node {
	return skipOuterExpressions(node, OuterExpressionKindsPartiallyEmittedExpressions)
}

func isNonNullChain(node *Node) bool {
	return isNonNullExpression(node) && !!(node.flags & NodeFlagsOptionalChain)
}

func isBreakOrContinueStatement(node *Node) bool {
	return node.kind == SyntaxKindBreakStatement || node.kind == SyntaxKindContinueStatement
}

func isNamedExportBindings(node *Node) bool {
	return node.kind == SyntaxKindNamespaceExport || node.kind == SyntaxKindNamedExports
}

func isJSDocPropertyLikeTag(node *Node) bool {
	return node.kind == SyntaxKindJSDocPropertyTag || node.kind == SyntaxKindJSDocParameterTag
}

// #endregion

// #region
// Node tests
//
// All node tests in the following list should *not* reference parent pointers so that
// they may be used with transformations.

func isNodeKind(kind SyntaxKind) bool {
	return kind >= SyntaxKindFirstNode
}

/**
 * True if kind is of some token syntax kind.
 * For example, this is true for an IfKeyword but not for an IfStatement.
 * Literals are considered tokens, except TemplateLiteral, but does include TemplateHead/Middle/Tail.
 */

func isTokenKind(kind SyntaxKind) bool {
	return kind >= SyntaxKindFirstToken && kind <= SyntaxKindLastToken
}

/**
 * True if node is of some token syntax kind.
 * For example, this is true for an IfKeyword but not for an IfStatement.
 * Literals are considered tokens, except TemplateLiteral, but does include TemplateHead/Middle/Tail.
 */

func isToken(n *Node) bool {
	return isTokenKind(n.kind)
}

// Node Arrays

func isNodeArray(array []T) bool {
	return hasProperty(array, "pos") && hasProperty(array, "end")
}

// Literals

func isLiteralKind(kind SyntaxKind) bool {
	return SyntaxKindFirstLiteralToken <= kind && kind <= SyntaxKindLastLiteralToken
}

func isLiteralExpression(node *Node) bool {
	return isLiteralKind(node.kind)
}

/** @internal */

func isLiteralExpressionOfObject(node *Node) bool {
	switch node.kind {
	case SyntaxKindObjectLiteralExpression,
		SyntaxKindArrayLiteralExpression,
		SyntaxKindRegularExpressionLiteral,
		SyntaxKindFunctionExpression,
		SyntaxKindClassExpression:
		return true
	}
	return false
}

// Pseudo-literals

func isTemplateLiteralKind(kind SyntaxKind) bool {
	return SyntaxKindFirstTemplateToken <= kind && kind <= SyntaxKindLastTemplateToken
}

func isTemplateLiteralToken(node *Node) bool {
	return isTemplateLiteralKind(node.kind)
}

func isTemplateMiddleOrTemplateTail(node *Node) bool {
	kind := node.kind
	return kind == SyntaxKindTemplateMiddle || kind == SyntaxKindTemplateTail
}

func isImportOrExportSpecifier(node *Node) bool {
	return isImportSpecifier(node) || isExportSpecifier(node)
}

func isTypeOnlyImportDeclaration(node *Node) bool {
	switch node.kind {
	case SyntaxKindImportSpecifier:
		return (node.(ImportSpecifier)).isTypeOnly || (node.(ImportSpecifier)).parent.parent.isTypeOnly
	case SyntaxKindNamespaceImport:
		return (node.(NamespaceImport)).parent.isTypeOnly
	case SyntaxKindImportClause,
		SyntaxKindImportEqualsDeclaration:
		return (node /* as ImportClause | ImportEqualsDeclaration */).isTypeOnly
	}
	return false
}

func isTypeOnlyExportDeclaration(node *Node) bool {
	switch node.kind {
	case SyntaxKindExportSpecifier:
		return (node.(ExportSpecifier)).isTypeOnly || (node.(ExportSpecifier)).parent.parent.isTypeOnly
	case SyntaxKindExportDeclaration:
		return (node.(ExportDeclaration)).isTypeOnly && !!(node.(ExportDeclaration)).moduleSpecifier && !(node.(ExportDeclaration)).exportClause
	case SyntaxKindNamespaceExport:
		return (node.(NamespaceExport)).parent.isTypeOnly
	}
	return false
}

func isTypeOnlyImportOrExportDeclaration(node *Node) bool {
	return isTypeOnlyImportDeclaration(node) || isTypeOnlyExportDeclaration(node)
}

func isStringTextContainingNode(node *Node) bool {
	return node.kind == SyntaxKindStringLiteral || isTemplateLiteralKind(node.kind)
}

func isImportAttributeName(node *Node) bool {
	return isStringLiteral(node) || isIdentifier(node)
}

// Identifiers

func isGeneratedIdentifier(node *Node) bool {
	return isIdentifier(node) && node.emitNode. /* ? */ autoGenerate != nil
}

/** @internal */

func isGeneratedPrivateIdentifier(node *Node) bool {
	return isPrivateIdentifier(node) && node.emitNode. /* ? */ autoGenerate != nil
}

/** @internal */

func isFileLevelReservedGeneratedIdentifier(node GeneratedIdentifier) bool {
	flags := node.emitNode.autoGenerate.flags
	return !!(flags & GeneratedIdentifierFlagsFileLevel) && !!(flags & GeneratedIdentifierFlagsOptimistic) && !!(flags & GeneratedIdentifierFlagsReservedInNestedScopes)
}

// Private Identifiers

func isPrivateIdentifierClassElementDeclaration(node *Node) bool {
	return (isPropertyDeclaration(node) || isMethodOrAccessor(node)) && isPrivateIdentifier(node.name)
}

/** @internal */

func isPrivateIdentifierPropertyAccessExpression(node *Node) bool {
	return isPropertyAccessExpression(node) && isPrivateIdentifier(node.name)
}

// Keywords

func isModifierKind(token SyntaxKind) bool {
	switch token {
	case SyntaxKindAbstractKeyword,
		SyntaxKindAccessorKeyword,
		SyntaxKindAsyncKeyword,
		SyntaxKindConstKeyword,
		SyntaxKindDeclareKeyword,
		SyntaxKindDefaultKeyword,
		SyntaxKindExportKeyword,
		SyntaxKindInKeyword,
		SyntaxKindPublicKeyword,
		SyntaxKindPrivateKeyword,
		SyntaxKindProtectedKeyword,
		SyntaxKindReadonlyKeyword,
		SyntaxKindStaticKeyword,
		SyntaxKindOutKeyword,
		SyntaxKindOverrideKeyword:
		return true
	}
	return false
}

/** @internal */

func isParameterPropertyModifier(kind SyntaxKind) bool {
	return !!(modifierToFlag(kind) & ModifierFlagsParameterPropertyModifier)
}

/** @internal */

func isClassMemberModifier(idToken SyntaxKind) bool {
	return isParameterPropertyModifier(idToken) || idToken == SyntaxKindStaticKeyword || idToken == SyntaxKindOverrideKeyword || idToken == SyntaxKindAccessorKeyword
}

func isModifier(node *Node) bool {
	return isModifierKind(node.kind)
}

func isEntityName(node *Node) bool {
	kind := node.kind
	return kind == SyntaxKindQualifiedName || kind == SyntaxKindIdentifier
}

func isPropertyName(node *Node) bool {
	kind := node.kind
	return kind == SyntaxKindIdentifier || kind == SyntaxKindPrivateIdentifier || kind == SyntaxKindStringLiteral || kind == SyntaxKindNumericLiteral || kind == SyntaxKindComputedPropertyName
}

func isBindingName(node *Node) bool {
	kind := node.kind
	return kind == SyntaxKindIdentifier || kind == SyntaxKindObjectBindingPattern || kind == SyntaxKindArrayBindingPattern
}

// Functions

func isFunctionLike(node *Node) bool {
	return !!node && isFunctionLikeKind(node.kind)
}

/** @internal */

func isFunctionLikeOrClassStaticBlockDeclaration(node *Node) bool {
	return !!node && (isFunctionLikeKind(node.kind) || isClassStaticBlockDeclaration(node))
}

/** @internal */

func isFunctionLikeDeclaration(node *Node) bool {
	return node && isFunctionLikeDeclarationKind(node.kind)
}

/** @internal */

func isBooleanLiteral(node *Node) bool {
	return node.kind == SyntaxKindTrueKeyword || node.kind == SyntaxKindFalseKeyword
}

func isFunctionLikeDeclarationKind(kind SyntaxKind) bool {
	switch kind {
	case SyntaxKindFunctionDeclaration,
		SyntaxKindMethodDeclaration,
		SyntaxKindConstructor,
		SyntaxKindGetAccessor,
		SyntaxKindSetAccessor,
		SyntaxKindFunctionExpression,
		SyntaxKindArrowFunction:
		return true
	default:
		return false
	}
}

/** @internal */

func isFunctionLikeKind(kind SyntaxKind) bool {
	switch kind {
	case SyntaxKindMethodSignature,
		SyntaxKindCallSignature,
		SyntaxKindJSDocSignature,
		SyntaxKindConstructSignature,
		SyntaxKindIndexSignature,
		SyntaxKindFunctionType,
		SyntaxKindJSDocFunctionType,
		SyntaxKindConstructorType:
		return true
	default:
		return isFunctionLikeDeclarationKind(kind)
	}
}

/** @internal */

func isFunctionOrModuleBlock(node *Node) bool {
	return isSourceFile(node) || isModuleBlock(node) || isBlock(node) && isFunctionLike(node.parent)
}

// Classes
func isClassElement(node *Node) bool {
	kind := node.kind
	return kind == SyntaxKindConstructor || kind == SyntaxKindPropertyDeclaration || kind == SyntaxKindMethodDeclaration || kind == SyntaxKindGetAccessor || kind == SyntaxKindSetAccessor || kind == SyntaxKindIndexSignature || kind == SyntaxKindClassStaticBlockDeclaration || kind == SyntaxKindSemicolonClassElement
}

func isClassLike(node *Node) bool {
	return node && (node.kind == SyntaxKindClassDeclaration || node.kind == SyntaxKindClassExpression)
}

func isAccessor(node *Node) bool {
	return node && (node.kind == SyntaxKindGetAccessor || node.kind == SyntaxKindSetAccessor)
}

func isAutoAccessorPropertyDeclaration(node *Node) bool {
	return isPropertyDeclaration(node) && hasAccessorModifier(node)
}

/** @internal */

func isClassInstanceProperty(node Declaration) bool {
	if isInJSFile(node) && isExpandoPropertyDeclaration(node) {
		return (!isBindableStaticAccessExpression(node) || !isPrototypeAccess(node.expression)) && !isBindableStaticNameExpression(node /*excludeThisKeyword*/, true)
	}
	return node.parent && isClassLike(node.parent) && isPropertyDeclaration(node) && !hasAccessorModifier(node)
}

/** @internal */

func isMethodOrAccessor(node *Node) bool {
	switch node.kind {
	case SyntaxKindMethodDeclaration,
		SyntaxKindGetAccessor,
		SyntaxKindSetAccessor:
		return true
	default:
		return false
	}
}

// Type members

func isModifierLike(node *Node) bool {
	return isModifier(node) || isDecorator(node)
}

func isTypeElement(node *Node) bool {
	kind := node.kind
	return kind == SyntaxKindConstructSignature || kind == SyntaxKindCallSignature || kind == SyntaxKindPropertySignature || kind == SyntaxKindMethodSignature || kind == SyntaxKindIndexSignature || kind == SyntaxKindGetAccessor || kind == SyntaxKindSetAccessor || kind == SyntaxKindNotEmittedTypeElement
}

func isClassOrTypeElement(node *Node) bool {
	return isTypeElement(node) || isClassElement(node)
}

func isObjectLiteralElementLike(node *Node) bool {
	kind := node.kind
	return kind == SyntaxKindPropertyAssignment || kind == SyntaxKindShorthandPropertyAssignment || kind == SyntaxKindSpreadAssignment || kind == SyntaxKindMethodDeclaration || kind == SyntaxKindGetAccessor || kind == SyntaxKindSetAccessor
}

// Type

func isTypeNode(node *Node) bool {
	return isTypeNodeKind(node.kind)
}

func isFunctionOrConstructorTypeNode(node *Node) bool {
	switch node.kind {
	case SyntaxKindFunctionType,
		SyntaxKindConstructorType:
		return true
	}

	return false
}

// Binding patterns

func isBindingPattern(node *Node) bool {
	if node {
		kind := node.kind
		return kind == SyntaxKindArrayBindingPattern || kind == SyntaxKindObjectBindingPattern
	}

	return false
}

/** @internal */

func isAssignmentPattern(node *Node) bool {
	kind := node.kind
	return kind == SyntaxKindArrayLiteralExpression || kind == SyntaxKindObjectLiteralExpression
}

func isArrayBindingElement(node *Node) bool {
	kind := node.kind
	return kind == SyntaxKindBindingElement || kind == SyntaxKindOmittedExpression
}

/**
 * Determines whether the BindingOrAssignmentElement is a BindingElement-like declaration
 *
 * @internal
 */

func isDeclarationBindingElement(bindingElement BindingOrAssignmentElement) bool {
	switch bindingElement.kind {
	case SyntaxKindVariableDeclaration,
		SyntaxKindParameter,
		SyntaxKindBindingElement:
		return true
	}

	return false
}

/** @internal */

func isBindingOrAssignmentElement(node *Node) bool {
	return isVariableDeclaration(node) || isParameter(node) || isObjectBindingOrAssignmentElement(node) || isArrayBindingOrAssignmentElement(node)
}

/**
 * Determines whether a node is a BindingOrAssignmentPattern
 *
 * @internal
 */

func isBindingOrAssignmentPattern(node BindingOrAssignmentElementTarget) bool {
	return isObjectBindingOrAssignmentPattern(node) || isArrayBindingOrAssignmentPattern(node)
}

/**
 * Determines whether a node is an ObjectBindingOrAssignmentPattern
 *
 * @internal
 */

func isObjectBindingOrAssignmentPattern(node BindingOrAssignmentElementTarget) bool {
	switch node.kind {
	case SyntaxKindObjectBindingPattern,
		SyntaxKindObjectLiteralExpression:
		return true
	}

	return false
}

/** @internal */

func isObjectBindingOrAssignmentElement(node *Node) bool {
	switch node.kind {
	case SyntaxKindBindingElement,
		SyntaxKindPropertyAssignment,
		SyntaxKindShorthandPropertyAssignment,
		SyntaxKindSpreadAssignment:
		return true
	}
	return false
}

/**
 * Determines whether a node is an ArrayBindingOrAssignmentPattern
 *
 * @internal
 */

func isArrayBindingOrAssignmentPattern(node BindingOrAssignmentElementTarget) bool {
	switch node.kind {
	case SyntaxKindArrayBindingPattern,
		SyntaxKindArrayLiteralExpression:
		return true
	}

	return false
}

/** @internal */

func isArrayBindingOrAssignmentElement(node *Node) bool {
	switch node.kind {
	case SyntaxKindBindingElement,
		SyntaxKindOmittedExpression,
		SyntaxKindSpreadElement,
		SyntaxKindArrayLiteralExpression,
		SyntaxKindObjectLiteralExpression,
		SyntaxKindIdentifier,
		SyntaxKindPropertyAccessExpression,
		SyntaxKindElementAccessExpression:
		return true
	}
	return isAssignmentExpression(node /*excludeCompoundAssignment*/, true)
	// AssignmentElement
}

/** @internal */

func isPropertyAccessOrQualifiedNameOrImportTypeNode(node *Node) bool {
	kind := node.kind
	return kind == SyntaxKindPropertyAccessExpression || kind == SyntaxKindQualifiedName || kind == SyntaxKindImportType
}

// Expression

func isPropertyAccessOrQualifiedName(node *Node) bool {
	kind := node.kind
	return kind == SyntaxKindPropertyAccessExpression || kind == SyntaxKindQualifiedName
}

/** @internal */

func isCallLikeOrFunctionLikeExpression(node *Node) bool {
	return isCallLikeExpression(node) || isFunctionExpressionOrArrowFunction(node)
}

func isCallLikeExpression(node *Node) bool {
	switch node.kind {
	case SyntaxKindJsxOpeningElement,
		SyntaxKindJsxSelfClosingElement,
		SyntaxKindCallExpression,
		SyntaxKindNewExpression,
		SyntaxKindTaggedTemplateExpression,
		SyntaxKindDecorator:
		return true
	default:
		return false
	}
}

func isCallOrNewExpression(node *Node) bool {
	return node.kind == SyntaxKindCallExpression || node.kind == SyntaxKindNewExpression
}

func isTemplateLiteral(node *Node) bool {
	kind := node.kind
	return kind == SyntaxKindTemplateExpression || kind == SyntaxKindNoSubstitutionTemplateLiteral
}

func isLeftHandSideExpression(node *Node) bool {
	return isLeftHandSideExpressionKind(skipPartiallyEmittedExpressions(node).kind)
}

func isLeftHandSideExpressionKind(kind SyntaxKind) bool {
	switch kind {
	case SyntaxKindPropertyAccessExpression,
		SyntaxKindElementAccessExpression,
		SyntaxKindNewExpression,
		SyntaxKindCallExpression,
		SyntaxKindJsxElement,
		SyntaxKindJsxSelfClosingElement,
		SyntaxKindJsxFragment,
		SyntaxKindTaggedTemplateExpression,
		SyntaxKindArrayLiteralExpression,
		SyntaxKindParenthesizedExpression,
		SyntaxKindObjectLiteralExpression,
		SyntaxKindClassExpression,
		SyntaxKindFunctionExpression,
		SyntaxKindIdentifier,
		SyntaxKindPrivateIdentifier,
		SyntaxKindRegularExpressionLiteral,
		SyntaxKindNumericLiteral,
		SyntaxKindBigIntLiteral,
		SyntaxKindStringLiteral,
		SyntaxKindNoSubstitutionTemplateLiteral,
		SyntaxKindTemplateExpression,
		SyntaxKindFalseKeyword,
		SyntaxKindNullKeyword,
		SyntaxKindThisKeyword,
		SyntaxKindTrueKeyword,
		SyntaxKindSuperKeyword,
		SyntaxKindNonNullExpression,
		SyntaxKindExpressionWithTypeArguments,
		SyntaxKindMetaProperty,
		SyntaxKindImportKeyword,
		SyntaxKindMissingDeclaration:
		return true
	default:
		return false
	}
}

/** @internal */

func isUnaryExpression(node *Node) bool {
	return isUnaryExpressionKind(skipPartiallyEmittedExpressions(node).kind)
}

func isUnaryExpressionKind(kind SyntaxKind) bool {
	switch kind {
	case SyntaxKindPrefixUnaryExpression,
		SyntaxKindPostfixUnaryExpression,
		SyntaxKindDeleteExpression,
		SyntaxKindTypeOfExpression,
		SyntaxKindVoidExpression,
		SyntaxKindAwaitExpression,
		SyntaxKindTypeAssertionExpression:
		return true
	default:
		return isLeftHandSideExpressionKind(kind)
	}
}

/** @internal */

func isUnaryExpressionWithWrite(expr *Node) bool {
	switch expr.kind {
	case SyntaxKindPostfixUnaryExpression:
		return true
	case SyntaxKindPrefixUnaryExpression:
		return (expr.(PrefixUnaryExpression)).operator == SyntaxKindPlusPlusToken || (expr.(PrefixUnaryExpression)).operator == SyntaxKindMinusMinusToken
	default:
		return false
	}
}

func isLiteralTypeLiteral(node *Node) bool {
	switch node.kind {
	case SyntaxKindNullKeyword,
		SyntaxKindTrueKeyword,
		SyntaxKindFalseKeyword,
		SyntaxKindPrefixUnaryExpression:
		return true
	default:
		return isLiteralExpression(node)
	}
}

/**
 * Determines whether a node is an expression based only on its kind.
 */

func isExpression(node *Node) bool {
	return isExpressionKind(skipPartiallyEmittedExpressions(node).kind)
}

func isExpressionKind(kind SyntaxKind) bool {
	switch kind {
	case SyntaxKindConditionalExpression,
		SyntaxKindYieldExpression,
		SyntaxKindArrowFunction,
		SyntaxKindBinaryExpression,
		SyntaxKindSpreadElement,
		SyntaxKindAsExpression,
		SyntaxKindOmittedExpression,
		SyntaxKindCommaListExpression,
		SyntaxKindPartiallyEmittedExpression,
		SyntaxKindSatisfiesExpression:
		return true
	default:
		return isUnaryExpressionKind(kind)
	}
}

func isAssertionExpression(node *Node) bool {
	kind := node.kind
	return kind == SyntaxKindTypeAssertionExpression || kind == SyntaxKindAsExpression
}

// Statement

/* OVERLOAD: export function isIterationStatement(node: Node, lookInLabeledStatements: false): node is IterationStatement; */
/* OVERLOAD: export function isIterationStatement(node: Node, lookInLabeledStatements: boolean): node is IterationStatement | LabeledStatement; */
func isIterationStatement(node *Node, lookInLabeledStatements bool) bool {
	switch node.kind {
	case SyntaxKindForStatement,
		SyntaxKindForInStatement,
		SyntaxKindForOfStatement,
		SyntaxKindDoStatement,
		SyntaxKindWhileStatement:
		return true
	case SyntaxKindLabeledStatement:
		return lookInLabeledStatements && isIterationStatement((node.(LabeledStatement)).statement, lookInLabeledStatements)
	}

	return false
}

func isScopeMarker(node *Node) bool {
	return isExportAssignment(node) || isExportDeclaration(node)
}

/** @internal */

func hasScopeMarker(statements []Statement) bool {
	return some(statements, isScopeMarker)
}

/** @internal */

func needsScopeMarker(result Statement) bool {
	return !isAnyImportOrReExport(result) && !isExportAssignment(result) && !hasSyntacticModifier(result, ModifierFlagsExport) && !isAmbientModule(result)
}

/** @internal */

func isExternalModuleIndicator(result Statement) bool {
	// Exported top-level member indicates moduleness
	return isAnyImportOrReExport(result) || isExportAssignment(result) || hasSyntacticModifier(result, ModifierFlagsExport)
}

/** @internal */

func isForInOrOfStatement(node *Node) bool {
	return node.kind == SyntaxKindForInStatement || node.kind == SyntaxKindForOfStatement
}

// Element

func isConciseBody(node *Node) bool {
	return isBlock(node) || isExpression(node)
}

/** @internal */

func isFunctionBody(node *Node) bool {
	return isBlock(node)
}

func isForInitializer(node *Node) bool {
	return isVariableDeclarationList(node) || isExpression(node)
}

func isModuleBody(node *Node) bool {
	kind := node.kind
	return kind == SyntaxKindModuleBlock || kind == SyntaxKindModuleDeclaration || kind == SyntaxKindIdentifier
}

/** @internal @knipignore */

func isNamespaceBody(node *Node) bool {
	kind := node.kind
	return kind == SyntaxKindModuleBlock || kind == SyntaxKindModuleDeclaration
}

/** @internal @knipignore */

func isJSDocNamespaceBody(node *Node) bool {
	kind := node.kind
	return kind == SyntaxKindIdentifier || kind == SyntaxKindModuleDeclaration
}

func isNamedImportBindings(node *Node) bool {
	kind := node.kind
	return kind == SyntaxKindNamedImports || kind == SyntaxKindNamespaceImport
}

/** @internal */

func isModuleOrEnumDeclaration(node *Node) bool {
	return node.kind == SyntaxKindModuleDeclaration || node.kind == SyntaxKindEnumDeclaration
}

/** @internal */

func canHaveSymbol(node *Node) bool {
	// NOTE: This should cover all possible declarations except MissingDeclaration and SemicolonClassElement
	//       since they aren't actually declarations and can't have a symbol.
	switch node.kind {
	case SyntaxKindArrowFunction,
		SyntaxKindBinaryExpression,
		SyntaxKindBindingElement,
		SyntaxKindCallExpression,
		SyntaxKindCallSignature,
		SyntaxKindClassDeclaration,
		SyntaxKindClassExpression,
		SyntaxKindClassStaticBlockDeclaration,
		SyntaxKindConstructor,
		SyntaxKindConstructorType,
		SyntaxKindConstructSignature,
		SyntaxKindElementAccessExpression,
		SyntaxKindEnumDeclaration,
		SyntaxKindEnumMember,
		SyntaxKindExportAssignment,
		SyntaxKindExportDeclaration,
		SyntaxKindExportSpecifier,
		SyntaxKindFunctionDeclaration,
		SyntaxKindFunctionExpression,
		SyntaxKindFunctionType,
		SyntaxKindGetAccessor,
		SyntaxKindIdentifier,
		SyntaxKindImportClause,
		SyntaxKindImportEqualsDeclaration,
		SyntaxKindImportSpecifier,
		SyntaxKindIndexSignature,
		SyntaxKindInterfaceDeclaration,
		SyntaxKindJSDocCallbackTag,
		SyntaxKindJSDocEnumTag,
		SyntaxKindJSDocFunctionType,
		SyntaxKindJSDocParameterTag,
		SyntaxKindJSDocPropertyTag,
		SyntaxKindJSDocSignature,
		SyntaxKindJSDocTypedefTag,
		SyntaxKindJSDocTypeLiteral,
		SyntaxKindJsxAttribute,
		SyntaxKindJsxAttributes,
		SyntaxKindJsxSpreadAttribute,
		SyntaxKindMappedType,
		SyntaxKindMethodDeclaration,
		SyntaxKindMethodSignature,
		SyntaxKindModuleDeclaration,
		SyntaxKindNamedTupleMember,
		SyntaxKindNamespaceExport,
		SyntaxKindNamespaceExportDeclaration,
		SyntaxKindNamespaceImport,
		SyntaxKindNewExpression,
		SyntaxKindNoSubstitutionTemplateLiteral,
		SyntaxKindNumericLiteral,
		SyntaxKindObjectLiteralExpression,
		SyntaxKindParameter,
		SyntaxKindPropertyAccessExpression,
		SyntaxKindPropertyAssignment,
		SyntaxKindPropertyDeclaration,
		SyntaxKindPropertySignature,
		SyntaxKindSetAccessor,
		SyntaxKindShorthandPropertyAssignment,
		SyntaxKindSourceFile,
		SyntaxKindSpreadAssignment,
		SyntaxKindStringLiteral,
		SyntaxKindTypeAliasDeclaration,
		SyntaxKindTypeLiteral,
		SyntaxKindTypeParameter,
		SyntaxKindVariableDeclaration:
		return true
	default:
		return false
	}
}

/** @internal */

func canHaveLocals(node *Node) bool {
	switch node.kind {
	case SyntaxKindArrowFunction,
		SyntaxKindBlock,
		SyntaxKindCallSignature,
		SyntaxKindCaseBlock,
		SyntaxKindCatchClause,
		SyntaxKindClassStaticBlockDeclaration,
		SyntaxKindConditionalType,
		SyntaxKindConstructor,
		SyntaxKindConstructorType,
		SyntaxKindConstructSignature,
		SyntaxKindForStatement,
		SyntaxKindForInStatement,
		SyntaxKindForOfStatement,
		SyntaxKindFunctionDeclaration,
		SyntaxKindFunctionExpression,
		SyntaxKindFunctionType,
		SyntaxKindGetAccessor,
		SyntaxKindIndexSignature,
		SyntaxKindJSDocCallbackTag,
		SyntaxKindJSDocEnumTag,
		SyntaxKindJSDocFunctionType,
		SyntaxKindJSDocSignature,
		SyntaxKindJSDocTypedefTag,
		SyntaxKindMappedType,
		SyntaxKindMethodDeclaration,
		SyntaxKindMethodSignature,
		SyntaxKindModuleDeclaration,
		SyntaxKindSetAccessor,
		SyntaxKindSourceFile,
		SyntaxKindTypeAliasDeclaration:
		return true
	default:
		return false
	}
}

func isDeclarationKind(kind SyntaxKind) bool {
	return kind == SyntaxKindArrowFunction || kind == SyntaxKindBindingElement || kind == SyntaxKindClassDeclaration || kind == SyntaxKindClassExpression || kind == SyntaxKindClassStaticBlockDeclaration || kind == SyntaxKindConstructor || kind == SyntaxKindEnumDeclaration || kind == SyntaxKindEnumMember || kind == SyntaxKindExportSpecifier || kind == SyntaxKindFunctionDeclaration || kind == SyntaxKindFunctionExpression || kind == SyntaxKindGetAccessor || kind == SyntaxKindImportClause || kind == SyntaxKindImportEqualsDeclaration || kind == SyntaxKindImportSpecifier || kind == SyntaxKindInterfaceDeclaration || kind == SyntaxKindJsxAttribute || kind == SyntaxKindMethodDeclaration || kind == SyntaxKindMethodSignature || kind == SyntaxKindModuleDeclaration || kind == SyntaxKindNamespaceExportDeclaration || kind == SyntaxKindNamespaceImport || kind == SyntaxKindNamespaceExport || kind == SyntaxKindParameter || kind == SyntaxKindPropertyAssignment || kind == SyntaxKindPropertyDeclaration || kind == SyntaxKindPropertySignature || kind == SyntaxKindSetAccessor || kind == SyntaxKindShorthandPropertyAssignment || kind == SyntaxKindTypeAliasDeclaration || kind == SyntaxKindTypeParameter || kind == SyntaxKindVariableDeclaration || kind == SyntaxKindJSDocTypedefTag || kind == SyntaxKindJSDocCallbackTag || kind == SyntaxKindJSDocPropertyTag || kind == SyntaxKindNamedTupleMember
}

func isDeclarationStatementKind(kind SyntaxKind) bool {
	return kind == SyntaxKindFunctionDeclaration || kind == SyntaxKindMissingDeclaration || kind == SyntaxKindClassDeclaration || kind == SyntaxKindInterfaceDeclaration || kind == SyntaxKindTypeAliasDeclaration || kind == SyntaxKindEnumDeclaration || kind == SyntaxKindModuleDeclaration || kind == SyntaxKindImportDeclaration || kind == SyntaxKindImportEqualsDeclaration || kind == SyntaxKindExportDeclaration || kind == SyntaxKindExportAssignment || kind == SyntaxKindNamespaceExportDeclaration
}

func isStatementKindButNotDeclarationKind(kind SyntaxKind) bool {
	return kind == SyntaxKindBreakStatement || kind == SyntaxKindContinueStatement || kind == SyntaxKindDebuggerStatement || kind == SyntaxKindDoStatement || kind == SyntaxKindExpressionStatement || kind == SyntaxKindEmptyStatement || kind == SyntaxKindForInStatement || kind == SyntaxKindForOfStatement || kind == SyntaxKindForStatement || kind == SyntaxKindIfStatement || kind == SyntaxKindLabeledStatement || kind == SyntaxKindReturnStatement || kind == SyntaxKindSwitchStatement || kind == SyntaxKindThrowStatement || kind == SyntaxKindTryStatement || kind == SyntaxKindVariableStatement || kind == SyntaxKindWhileStatement || kind == SyntaxKindWithStatement || kind == SyntaxKindNotEmittedStatement
}

/** @internal */

func isDeclaration(node *Node) bool {
	if node.kind == SyntaxKindTypeParameter {
		return (node.parent && node.parent.kind != SyntaxKindJSDocTemplateTag) || isInJSFile(node)
	}

	return isDeclarationKind(node.kind)
}

func isDeclarationStatement(node *Node) bool {
	return isDeclarationStatementKind(node.kind)
}

/**
 * Determines whether the node is a statement that is not also a declaration
 *
 * @internal
 */

func isStatementButNotDeclaration(node *Node) bool {
	return isStatementKindButNotDeclarationKind(node.kind)
}

func isStatement(node *Node) bool {
	kind := node.kind
	return isStatementKindButNotDeclarationKind(kind) || isDeclarationStatementKind(kind) || isBlockStatement(node)
}

func isBlockStatement(node *Node) bool {
	if node.kind != SyntaxKindBlock {
		return false
	}
	if node.parent != nil {
		if node.parent.kind == SyntaxKindTryStatement || node.parent.kind == SyntaxKindCatchClause {
			return false
		}
	}
	return !isFunctionBlock(node)
}

// TODO(jakebailey): should we be exporting this function and not isStatement?

func isStatementOrBlock(node *Node) bool {
	kind := node.kind
	return isStatementKindButNotDeclarationKind(kind) || isDeclarationStatementKind(kind) || kind == SyntaxKindBlock
}

// Module references

func isModuleReference(node *Node) bool {
	kind := node.kind
	return kind == SyntaxKindExternalModuleReference || kind == SyntaxKindQualifiedName || kind == SyntaxKindIdentifier
}

// JSX

func isJsxTagNameExpression(node *Node) bool {
	kind := node.kind
	return kind == SyntaxKindThisKeyword || kind == SyntaxKindIdentifier || kind == SyntaxKindPropertyAccessExpression || kind == SyntaxKindJsxNamespacedName
}

func isJsxChild(node *Node) bool {
	kind := node.kind
	return kind == SyntaxKindJsxElement || kind == SyntaxKindJsxExpression || kind == SyntaxKindJsxSelfClosingElement || kind == SyntaxKindJsxText || kind == SyntaxKindJsxFragment
}

func isJsxAttributeLike(node *Node) bool {
	kind := node.kind
	return kind == SyntaxKindJsxAttribute || kind == SyntaxKindJsxSpreadAttribute
}

func isStringLiteralOrJsxExpression(node *Node) bool {
	kind := node.kind
	return kind == SyntaxKindStringLiteral || kind == SyntaxKindJsxExpression
}

func isJsxOpeningLikeElement(node *Node) bool {
	kind := node.kind
	return kind == SyntaxKindJsxOpeningElement || kind == SyntaxKindJsxSelfClosingElement
}

// Clauses

func isCaseOrDefaultClause(node *Node) bool {
	kind := node.kind
	return kind == SyntaxKindCaseClause || kind == SyntaxKindDefaultClause
}

// JSDoc

func isJSDocNode(node *Node) bool {
	return node.kind >= SyntaxKindFirstJSDocNode && node.kind <= SyntaxKindLastJSDocNode
}

/** True if node is of a kind that may contain comment text. */

func isJSDocCommentContainingNode(node *Node) bool {
	return node.kind == SyntaxKindJSDoc || node.kind == SyntaxKindJSDocNamepathType || node.kind == SyntaxKindJSDocText || isJSDocLinkLike(node) || isJSDocTag(node) || isJSDocTypeLiteral(node) || isJSDocSignature(node)
}

// TODO: determine what this does before making it public.

func isJSDocTag(node *Node) bool {
	return node.kind >= SyntaxKindFirstJSDocTagNode && node.kind <= SyntaxKindLastJSDocTagNode
}

func isSetAccessor(node *Node) bool {
	return node.kind == SyntaxKindSetAccessor
}

func isGetAccessor(node *Node) bool {
	return node.kind == SyntaxKindGetAccessor
}

/**
 * True if has jsdoc nodes attached to it.
 *
 * @internal
 */
// TODO: GH#19856 Would like to return `node is Node & { jsDoc: JSDoc[] }` but it causes long compile times

func hasJSDocNodes(node *Node) bool {
	if !canHaveJSDoc(node) {
		return false
	}

	TODO_IDENTIFIER := node.(JSDocContainer)
	return !!jsDoc && jsDoc.length > 0
}

/**
 * True if has type node attached to it.
 *
 * @internal
 */

func hasType(node *Node) bool {
	return !!(node.(HasType)).type_
}

/**
 * True if has initializer node attached to it.
 *
 * @internal
 */

func hasInitializer(node *Node) bool {
	return !!(node.(HasInitializer)).initializer
}

/** True if has initializer node attached to it. */

func hasOnlyExpressionInitializer(node *Node) bool {
	switch node.kind {
	case SyntaxKindVariableDeclaration,
		SyntaxKindParameter,
		SyntaxKindBindingElement,
		SyntaxKindPropertyDeclaration,
		SyntaxKindPropertyAssignment,
		SyntaxKindEnumMember:
		return true
	default:
		return false
	}
}

func isObjectLiteralElement(node *Node) bool {
	return node.kind == SyntaxKindJsxAttribute || node.kind == SyntaxKindJsxSpreadAttribute || isObjectLiteralElementLike(node)
}

/** @internal */

func isTypeReferenceType(node *Node) bool {
	return node.kind == SyntaxKindTypeReference || node.kind == SyntaxKindExpressionWithTypeArguments
}

var MAX_SMI_X86 = 0x3fff_ffff

/** @internal */

func guessIndentation(lines []string) *number {
	indentation := MAX_SMI_X86
	for _, line := range lines {
		if !line.length {
			continue
		}
		i := 0
		for ; i < line.length && i < indentation; i++ {
			if !isWhiteSpaceLike(line.charCodeAt(i)) {
				break
			}
		}
		if i < indentation {
			indentation = i
		}
		if indentation == 0 {
			return 0
		}
	}
	if indentation == MAX_SMI_X86 {
		return nil
	} else {
		return indentation
	}
}

func isStringLiteralLike(node /* TODO(TS-TO-GO) TypeNode UnionType: Node | FileReference */ any) bool {
	return (node.(*Node)).kind == SyntaxKindStringLiteral || (node.(*Node)).kind == SyntaxKindNoSubstitutionTemplateLiteral
}

func isJSDocLinkLike(node *Node) bool {
	return node.kind == SyntaxKindJSDocLink || node.kind == SyntaxKindJSDocLinkCode || node.kind == SyntaxKindJSDocLinkPlain
}

func hasRestParameter(s /* TODO(TS-TO-GO) TypeNode UnionType: SignatureDeclaration | JSDocSignature */ any) bool {
	last := lastOrUndefined(s.parameters)
	return !!last && isRestParameter(last)
}

func isRestParameter(node /* TODO(TS-TO-GO) TypeNode UnionType: ParameterDeclaration | JSDocParameterTag */ any) bool {
	var type_ *TypeNode
	if isJSDocParameterTag(node) {
		type_ = (node.typeExpression && node.typeExpression.type_)
	} else {
		type_ = node.type_
	}
	return (node.(ParameterDeclaration)).dotDotDotToken != nil || !!type_ && type_.kind == SyntaxKindJSDocVariadicType
}

func hasInternalAnnotation(range_ CommentRange, sourceFile SourceFile) bool {
	comment := sourceFile.text.substring(range_.pos, range_.end)
	return comment.includes("@internal")
}

func isInternalDeclaration(node *Node, sourceFile SourceFile) bool {
	/* TODO(TS-TO-GO) QuestionQuestionEqualsToken BinaryExpression: sourceFile ??= getSourceFileOfNode(node) */ TODO
	parseTreeNode := getParseTreeNode(node)
	if parseTreeNode && parseTreeNode.kind == SyntaxKindParameter {
		paramIdx := (parseTreeNode.parent.(SignatureDeclaration)).parameters.indexOf(parseTreeNode.(ParameterDeclaration))
		var previousSibling *ParameterDeclaration
		if paramIdx > 0 {
			previousSibling = (parseTreeNode.parent.(SignatureDeclaration)).parameters[paramIdx-1]
		} else {
			previousSibling = nil
		}
		text := sourceFile.text
		var commentRanges *[]CommentRange
		if previousSibling {
			commentRanges = concatenate(getTrailingCommentRanges(text, skipTrivia(text, previousSibling.end+1 /*stopAfterLineBreak*/, false /*stopAtComments*/, true)), getLeadingCommentRanges(text, node.pos))
		} else {
			commentRanges = getTrailingCommentRanges(text, skipTrivia(text, node.pos /*stopAfterLineBreak*/, false /*stopAtComments*/, true))
		}
		return some(commentRanges) && hasInternalAnnotation(last(commentRanges), sourceFile)
	}
	leadingCommentRanges := parseTreeNode && getLeadingCommentRangesOfNode(parseTreeNode, sourceFile)
	return !!forEach(leadingCommentRanges, func(range_ CommentRange) bool {
		return hasInternalAnnotation(range_, sourceFile)
	})
}
